Verify downloads

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -1,5 +1,6 @@
 #!/usr/bin/make -f
 
+SHELL := /bin/bash
 
 %:
 	dh $@
@@ -13,6 +14,15 @@ stamp-%: %-3.2.0-1.i386.deb
 	dpkg-deb -x $< dir-$*
 	touch $@
 
-%.deb:
-	wget -O $@.tmp http://www.brother.com/pub/bsc/linux/packages/$@
-	mv $@.tmp $@
+define download =
+$2:
+	wget -O $2.tmp $1$2
+	if [[ $$$$(sha256sum "$2.tmp" | cut -d ' ' -f 1) != $3 ]]; then \
+		echo 'Failed to verify downloaded file $2' >&2; \
+		exit 1; \
+	fi
+	mv $2.tmp $2
+endef
+
+$(eval $(call download,http://www.brother.com/pub/bsc/linux/packages/,hll2300dlpr-3.2.0-1.i386.deb,9b576bcbd42aae22147d3934f8c0acd5184f31f03c7c1e97ad68c2e9f1517e24))
+$(eval $(call download,http://www.brother.com/pub/bsc/linux/packages/,hll2300dcupswrapper-3.2.0-1.i386.deb,1973b781a01c3c1777cbff19e816e48e442d891823b7454f2850d2d5edd2d4bb))
